export { AboutSection } from "./AboutSection";
import FeedbackSection from "./FeedbackSection";
export { AchievementsSection } from "./AchievementsSection";
export { ContactForm } from "./ContactForm";
export { ContactSection } from "./ContactSection";
export { ExperienceSection } from "./ExperienceSection";
export { HeroSection } from "./HeroSection";
export { ServicesSection } from "./ServicesSection";
export { TestimonialsSection } from "./TestimonialsSection";
export { EventsSection } from "./EventsSection";
export { FeedbackSection } from "./FeedbackSection";
// export { BlogSection } from "./BlogSection";
// export { EducationSection } from "./EducationSection";
// export { ProjectsSection } from "./ProjectsSection";
